import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head'

const Signup = () => {


  const router = useRouter()

  useEffect(() => {
    if (localStorage.getItem("myuser")) {
      router.push('/')
    }

  }, [])



  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [phone, setPhone] = useState('')
  const [intro, setIntro] = useState('')
  const [skills, setSkills] = useState('')
  const [clgName, setClgName] = useState('')
  const [branch, setBranch] = useState('')
  const [clgDesc, setClgDesc] = useState('')
  const [year, setYear] = useState('')


  const handleSubmit = async (e) => {

    e.preventDefault();
    const data = { name, email, intro, clgName, branch, clgDesc, skills, phone, password, year }
    let res = await fetch(`${process.env.NEXT_PUBLIC_HOST}/api/signup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })
    let response = await res.json()
    setEmail('')
    setName('')
    setPassword('')
    setBranch('')
    setClgDesc('')
    setClgName('')
    setIntro('')
    setPhone('')
    setSkills('')
    setYear('')

    if (response.success) {
      localStorage.setItem("myuser", JSON.stringify({ token: response.token, email: response.email }))
      toast.success('Your Account has been created ', {
        position: "top-left",
        autoClose: 2000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "dark",
      });
      setTimeout(() => {
        router.push(process.env.NEXT_PUBLIC_HOST);
      }, 2000);
    } else {
      toast.error("this email Id already registered !!", {
        position: "top-left",
        autoClose: 2000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "dark",
      });
    }


  }



  const handleChange = (e) => {
    if (e.target.name == "name") {
      setName(e.target.value)
    } else if (e.target.name == "password") {
      setPassword(e.target.value)
    } else if (e.target.name == "email") {
      setEmail(e.target.value)
    } else if (e.target.name == "phone") {
      setPhone(e.target.value)
    } else if (e.target.name == "aboutDesc") {
      setIntro(e.target.value)
    } else if (e.target.name == "skills") {
      setSkills(e.target.value.split(" "));
    } else if (e.target.name == "clgname") {
      setClgName(e.target.value)
    } else if (e.target.name == "branch") {
      setBranch(e.target.value)
    } else if (e.target.name == "clgDesc") {
      setClgDesc(e.target.value)
    } else if (e.target.name == "year") {
      setYear(e.target.value)
    }
  }



  return (
    <div>
      <Head>
        <title>Create your Account !</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex items-center justify-center bg-log h-[100%]'>
        <ToastContainer
          position="top-left"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />

        <div className='flex flex-col items-center drop-shadow-lg bg-slate-200 my-10'>
          <h1 className='text-center text-4xl font-bold mt-6'>Oruphones</h1>
          <p className='text-center mt-7 text-lg px-5'>Set your profile to connect with your friends</p>
          <form onSubmit={handleSubmit} method='POST' className='flex flex-col items-center'>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-2 md:gap-6 lg:gap-6 p-5 pl-0 md:pl-5">
              <div className=" text-blue-950 text-lg font-semibold p-4 pl-0 md:pl-4">
                <div className="mx-10 flex flex-col">
                  <label className='mt-10 text-xl font-semibold' htmlFor="name">Display Name</label>
                  <input required value={name} onChange={handleChange} className='rounded-lg mt-1 w-80 p-2 text-sm  bg-white' type="name" placeholder='name' id='name' name='name' />
                  <label className='mt-5 text-xl font-semibold' htmlFor="email">Email address</label>
                  <input required value={email} onChange={handleChange} className='rounded-lg mt-1 w-80 p-2 text-sm  bg-white' type="email" placeholder='email' id='email' name='email' />
                  <label className='mt-5 text-xl font-semibold' htmlFor="password">Password</label>
                  <input required value={password} onChange={handleChange} className='rounded-lg mt-1 w-80 p-2 text-sm  bg-white' type="password" placeholder='Password' id='name' name='password' />
                  <label className='mt-5 text-xl font-semibold' htmlFor="phone">Phone Number</label>
                  <input required value={phone} onChange={handleChange} className='rounded-lg mt-1 border-x-2 w-80 p-2 text-sm bg-white' type="phone" id='phone' placeholder='Phone' name='phone' />
                  <textarea required onChange={handleChange} value={intro} className='rounded-lg mt-3 border-x-2 w-80 p-2 text-sm bg-white' name="aboutDesc" placeholder='Introduce yourself with your key skills and achievements...' id="collegedesc" cols="4" rows="5"></textarea>
                </div>
              </div>

              <div className=" text-blue-950 text-lg font-semibold p-4 pl-0 md:pl-4">
                <div className="mx-10 flex flex-col">
                  <label className='mt-10 text-xl font-semibold' htmlFor="skills">Skills </label>
                  <input required onChange={handleChange} name='skills' className=' rounded-lg mt-1 w-80 p-2 text-sm  bg-white' type="text" placeholder='e.g. Nodejs Expressjs XML' id='skills' />
                  <label className='mt-5 text-xl font-semibold' htmlFor="collegeName">College Details</label>
                  <input required value={clgName} onChange={handleChange} name='clgname' className='rounded-lg mt-3 w-80 p-2 text-sm  bg-white' type="text" placeholder='Your College name' id='collegeName' />
                  <input required value={branch} onChange={handleChange} name='branch' className='rounded-lg mt-4 border-x-2 w-80 p-2 text-sm bg-white' type="branch" id='branch' placeholder='Your Branch' />
                  <label className='mt-5 text-xl font-semibold' htmlFor="password">Year</label>
                  <div className="flex mt-3">
                    <input required name='year' value={year} onChange={handleChange} placeholder='start year - end year' className=' mt-3 text-sm font-semibold px-3 py-1 rounded-sm shadow-md' type="text" />
                  </div>
                  <textarea required onChange={handleChange} className='rounded-lg mt-5 border-x-2 w-80 p-2 text-sm bg-white' name="clgDesc" placeholder='Introduce your college...' cols="8" rows="6" value={clgDesc}></textarea>
                </div>
              </div>
            </div>
            <button type='submit' className='bg-blue-500 text-white text-xl mt-5 py-2 px-6 rounded-lg drop-shadow-md'>Create Profile</button>
          </form>
          <span className='text-lg mt-4 mb-5 text-center'>Already have an Account ? <Link className='text-blue-500' href={"/login"}>Log in</Link></span>



        </div>



      </div >
    </div>
  )
}

export default Signup
